apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: keycloak-database }
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bgstore
    kind: ClusterSecretStore
  target:
    name: keycloak-database
    creationPolicy: Owner
    template: { type: kubernetes.io/basic-auth }
  data:
    - secretKey: username
      remoteRef:
        key: environments/production/keycloak-database
        property: POSTGRES_USER
    - secretKey: password
      remoteRef:
        key: environments/production/keycloak-database
        property: POSTGRES_PASSWORD
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata: { name: keycloak-postgresql }
spec:
  instances: 3
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret: { name: keycloak-database }
  storage: { size: 10Gi }
  monitoring: { enablePodMonitor: true }
