global:
  domain: bgstore.chanakanlabs.com
gateway: {create: true}
postgresql: {createCluster: true, instances: 3, storageSize: 20Gi}
secret:
  externalSecret: {enabled: true}
config: {traceSamplingProbability: '0.1'}
images:
  api:
    digest: sha256:c5b601469328996c656b065dff97fe3767f87631adee8a285b1722279a7974f2
  web:
    digest: sha256:4eda488871ae450e5fd882662f4a3f71bfcc8822b6b9ae540e9faaaa0a033627
