-- A play session is the checked-in part of a reservation's lifecycle, so the
-- session state lives on the reservation the floor already owns rather than in a
-- second aggregate that would have to be kept in step with it.
--
-- The fee is confirmed by an authorized role at check-out (see
-- docs/domain-model.md: "Check-out closes active play and visit state only after
-- the final fee is calculated or explicitly waived by an authorized role"), so
-- the payment method is recorded alongside the reservation's existing
-- total_price and actual_check_out columns. No card data is stored.
ALTER TABLE reservation
    ADD COLUMN payment_method VARCHAR(32);

ALTER TABLE reservation
    ADD CONSTRAINT ck_reservation_payment_method
        CHECK (payment_method IS NULL
            OR payment_method IN ('Cash', 'PromptPay', 'BankTransfer', 'Waived'));

-- Client assistance requests are durable so a retry is deduplicated by the
-- client-supplied request id instead of being recorded twice. They never close a
-- session or stop billing; only staff check-out does that.
CREATE TABLE session_assistance_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID NOT NULL,
    reservation_id VARCHAR(64) NOT NULL REFERENCES reservation (id) ON DELETE CASCADE,
    kind VARCHAR(32) NOT NULL,
    requested_by_subject VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_session_assistance_request_id UNIQUE (request_id),
    CONSTRAINT ck_session_assistance_kind CHECK (kind IN ('CallStaff', 'EndPlaying'))
);

CREATE INDEX ix_session_assistance_reservation ON session_assistance_request (reservation_id);
