-- A payment record is the billing module's operational trace of a confirmed fee.
-- Only successful charges are recorded: a declined charge aborts check-out,
-- leaves the session open for a retry, and never closes play. Cash is taken at
-- the counter and Waived closes the session without charging, so at most one
-- settlement exists per reservation. No card data is stored.
CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id VARCHAR(64) NOT NULL REFERENCES reservation (id) ON DELETE CASCADE,
    amount INTEGER NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) NOT NULL,
    method VARCHAR(32) NOT NULL
        CHECK (method IN ('Cash', 'PromptPay', 'BankTransfer', 'Waived')),
    status VARCHAR(16) NOT NULL CHECK (status IN ('Succeeded')),
    gateway VARCHAR(32) NOT NULL,
    gateway_reference VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_payment_reservation UNIQUE (reservation_id)
);

CREATE INDEX ix_payment_reservation ON payment (reservation_id);