CREATE TABLE store_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    branch VARCHAR(100) NOT NULL,
    capacity INTEGER NOT NULL,
    shape VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    active BOOLEAN NOT NULL,
    zone VARCHAR(100) NOT NULL,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_store_table_capacity CHECK (capacity BETWEEN 1 AND 100),
    CONSTRAINT ck_store_table_shape CHECK (shape IN ('Round', 'Square', 'Oval', 'Rectangle')),
    CONSTRAINT ck_store_table_status CHECK (status IN ('Available', 'Reserved', 'Occupied', 'Unavailable')),
    CONSTRAINT uq_store_table_name_branch UNIQUE (name, branch)
);

CREATE INDEX ix_store_table_branch ON store_table (branch);
CREATE INDEX ix_store_table_status ON store_table (status);

INSERT INTO store_table (id, name, branch, capacity, shape, status, active, zone, last_updated)
SELECT row_number() OVER (),
       'Table ' || row_number() OVER (),
       CASE WHEN row_number() OVER () <= 10 THEN 'Sukhumvit'
            WHEN row_number() OVER () <= 15 THEN 'Silom'
            ELSE 'Central Rama II' END,
       capacity,
       shape,
       status,
       active,
       zone,
       CURRENT_TIMESTAMP - age
FROM (VALUES
    (4, 'Round', 'Available', true, 'Main Hall', INTERVAL '30 minutes'),
    (2, 'Square', 'Available', true, 'Main Hall', INTERVAL '45 minutes'),
    (2, 'Square', 'Reserved', true, 'Private Room', INTERVAL '20 minutes'),
    (6, 'Round', 'Available', true, 'Main Hall', INTERVAL '1 hour'),
    (4, 'Round', 'Occupied', true, 'Main Hall', INTERVAL '10 minutes'),
    (8, 'Rectangle', 'Available', true, 'VIP', INTERVAL '2 hours'),
    (4, 'Square', 'Reserved', true, 'Main Hall', INTERVAL '50 minutes'),
    (2, 'Round', 'Available', true, 'Rooftop', INTERVAL '3 hours'),
    (6, 'Oval', 'Occupied', true, 'Main Hall', INTERVAL '15 minutes'),
    (10, 'Rectangle', 'Available', true, 'VIP', INTERVAL '4 hours'),
    (4, 'Square', 'Available', true, 'Main Hall', INTERVAL '40 minutes'),
    (6, 'Round', 'Reserved', true, 'Main Hall', INTERVAL '25 minutes'),
    (2, 'Square', 'Available', true, 'Rooftop', INTERVAL '2 hours'),
    (8, 'Rectangle', 'Occupied', true, 'Private Room', INTERVAL '5 minutes'),
    (4, 'Round', 'Available', true, 'Main Hall', INTERVAL '1 hour'),
    (4, 'Square', 'Available', true, 'Main Hall', INTERVAL '35 minutes'),
    (2, 'Round', 'Unavailable', false, 'Main Hall', INTERVAL '1 day'),
    (6, 'Oval', 'Reserved', true, 'VIP', INTERVAL '15 minutes'),
    (4, 'Round', 'Occupied', true, 'Main Hall', INTERVAL '8 minutes'),
    (8, 'Rectangle', 'Available', true, 'Rooftop', INTERVAL '5 hours')
) AS seed(capacity, shape, status, active, zone, age);

SELECT setval(pg_get_serial_sequence('store_table', 'id'), (SELECT max(id) FROM store_table));
