CREATE TABLE table_reservation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_id BIGINT NOT NULL REFERENCES store_table (id) ON DELETE CASCADE,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT ck_table_reservation_interval CHECK (ends_at > starts_at)
);

CREATE INDEX ix_table_reservation_table_ends
  ON table_reservation (table_id, ends_at);
